Added helm repo update

diff --git a/k8s/oc_helm/bin_sh/build_app b/k8s/oc_helm/bin_sh/build_app
--- a/k8s/oc_helm/bin_sh/build_app
+++ b/k8s/oc_helm/bin_sh/build_app
@@ -24,13 +24,24 @@ EOF
 exit
 fi
 
+if [ "$(which helm)" == "" ]; then
+   echo >&2 "ERROR: The 'helm' executable not found. Command aborted."
+   exit 1
+fi
+
+#
+# Add Hazelcast Helm repo
+#
+helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
+helm repo update
+echo ""
+
 #
 # Set license key
 #
 # Set license key
 IMDG_LICENSE_KEY_BASE64=$(echo -n "$IMDG_LICENSE_KEY" | base64)
 sed "s/<base64-hz-license-key>/$IMDG_LICENSE_KEY_BASE64/" "$APP_DIR/etc/hazelcast-enterprise/secret.yaml" > "$APP_DIR/hazelcast/secret.yaml"
-popd > /dev/null
 
 #
 # Display build information
